# Generated by Django 2.2.7 on 2019-11-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitcaCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=50)),
                ('pc_ip', models.CharField(max_length=50)),
                ('pc_cpu', models.CharField(max_length=100)),
                ('pc_ram', models.IntegerField(default=0)),
                ('pc_storage', models.CharField(max_length=50)),
                ('pc_hdmi', models.BooleanField(default=False)),
            ],
        ),
    ]
